name: web_unamsitou_flutter
description: "A new Flutter application with WebView"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.2
  url_launcher: ^6.1.10
  app_links: ^3.4.5  # Reemplaza uni_links

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true